create extension if not exists pgcrypto;

create table if not exists public.sections (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text not null default '',
  kind text not null default 'commands',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.sections(id) on delete cascade,
  name text not null,
  slug text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(section_id, slug)
);

create table if not exists public.entries (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.categories(id) on delete cascade,
  name text not null,
  code text not null default '',
  description text not null default '',
  uses_amount boolean not null default false,
  variants jsonb not null default '{}'::jsonb,
  levels jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sections_updated_at on public.sections;
create trigger sections_updated_at before update on public.sections for each row execute procedure public.set_updated_at();
drop trigger if exists categories_updated_at on public.categories;
create trigger categories_updated_at before update on public.categories for each row execute procedure public.set_updated_at();
drop trigger if exists entries_updated_at on public.entries;
create trigger entries_updated_at before update on public.entries for each row execute procedure public.set_updated_at();



create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'user')
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

revoke all on function public.handle_new_user() from public;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

alter table public.sections enable row level security;
alter table public.categories enable row level security;
alter table public.entries enable row level security;
alter table public.profiles enable row level security;

drop policy if exists sections_public_read on public.sections;
create policy sections_public_read on public.sections for select to anon, authenticated using (true);
drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select to anon, authenticated using (true);
drop policy if exists entries_public_read on public.entries;
create policy entries_public_read on public.entries for select to anon, authenticated using (true);

drop policy if exists sections_admin_write on public.sections;
create policy sections_admin_write on public.sections for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists categories_admin_write on public.categories;
create policy categories_admin_write on public.categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists entries_admin_write on public.entries;
create policy entries_admin_write on public.entries for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select to authenticated using (id = auth.uid());

grant select on public.sections, public.categories, public.entries to anon, authenticated;
grant insert, update, delete on public.sections, public.categories, public.entries to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.sections;
  alter publication supabase_realtime add table public.categories;
  alter publication supabase_realtime add table public.entries;
exception when duplicate_object then null;
end $$;

-- ============================================================
-- Damanhour City GM Helper catalog seed
-- ============================================================

-- Damanhour City GM Helper database seed
begin;
insert into public.sections (id,name,slug,description,kind,sort_order) values ('5318e887-bc84-530f-9991-af293f46d7cf','Discord Commands','discord','Discord commands from the existing Discord JSON.','commands',1) on conflict (slug) do update set name=excluded.name,description=excluded.description,kind=excluded.kind,sort_order=excluded.sort_order;
insert into public.sections (id,name,slug,description,kind,sort_order) values ('2222f37c-adad-54b2-aa3e-48d44c88c7eb','In-game Commands','ingame','In-game command catalog from the existing In-game JSON.','commands',2) on conflict (slug) do update set name=excluded.name,description=excluded.description,kind=excluded.kind,sort_order=excluded.sort_order;
insert into public.sections (id,name,slug,description,kind,sort_order) values ('f67d2d70-2b8f-587b-8c07-6724017a2014','Item Codes','items','Item and weapon generators from the original Helper.','generators',3) on conflict (slug) do update set name=excluded.name,description=excluded.description,kind=excluded.kind,sort_order=excluded.sort_order;
insert into public.sections (id,name,slug,description,kind,sort_order) values ('3d1e6e7b-9bb5-5177-ad0a-d2657c8b1977','Console Commands','console','Console commands and unique spawners from the original Helper.','console',4) on conflict (slug) do update set name=excluded.name,description=excluded.description,kind=excluded.kind,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('4e393434-1103-53d7-a55b-c9f7b6e08a29','5318e887-bc84-530f-9991-af293f46d7cf','Streaming / Nitro Commands', 'streaming-nitro-commands',1) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('4fce5718-428f-531d-be8f-8112d3d41311','5318e887-bc84-530f-9991-af293f46d7cf','Silk - Gold - Package Commands', 'silk-gold-package-commands',2) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('9c9a9eba-09e3-5c63-9df2-2e4b773f6dfb','5318e887-bc84-530f-9991-af293f46d7cf','CHAR Commands', 'char-commands',3) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('a9b982f6-a70b-5465-93a7-08edae95bafd','5318e887-bc84-530f-9991-af293f46d7cf','Quests Commands', 'quests-commands',4) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('47c36348-6a9c-5b8b-88e5-03d9991b08b4','5318e887-bc84-530f-9991-af293f46d7cf','Card Collection Commands', 'card-collection-commands',5) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('fe32aad1-0c98-55dc-9da1-ae617a5458ba','5318e887-bc84-530f-9991-af293f46d7cf','Ban Commands', 'ban-commands',6) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','2222f37c-adad-54b2-aa3e-48d44c88c7eb','Titles / Streaming Commands', 'titles-streaming-commands',7) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('97c4693d-56e8-5d8b-b0d3-0f2fed59201d','2222f37c-adad-54b2-aa3e-48d44c88c7eb','Silk / Gift Commands', 'silk-gift-commands',8) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('79c61f24-501f-58fa-bfa8-45b05d94be29','2222f37c-adad-54b2-aa3e-48d44c88c7eb','Character Commands', 'character-commands',9) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('e606ab8f-bee5-58c9-ad0e-14983be1a926','2222f37c-adad-54b2-aa3e-48d44c88c7eb','Inventory Commands', 'inventory-commands',10) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('32971820-af97-5614-830c-435b896bb1bb','2222f37c-adad-54b2-aa3e-48d44c88c7eb','Plus / FB Commands', 'plus-fb-commands',11) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('df70df0f-ac66-5886-bfd2-8571dd41cb2c','3d1e6e7b-9bb5-5177-ad0a-d2657c8b1977','Normal Commands', 'normal-commands',12) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('7c9a958e-f7b6-5c39-9fe2-02219c52dff7','3d1e6e7b-9bb5-5177-ad0a-d2657c8b1977','Normal EU', 'normal-eu',13) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','3d1e6e7b-9bb5-5177-ad0a-d2657c8b1977','Normal CH', 'normal-ch',14) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('85314461-a38c-592f-84c5-9ea7f23e4c18','3d1e6e7b-9bb5-5177-ad0a-d2657c8b1977','Zealot Uniques', 'zealot-uniques',15) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('5b2bef5d-9145-5b55-8a78-16acea9d24b8','3d1e6e7b-9bb5-5177-ad0a-d2657c8b1977','Temple Uniques', 'temple-uniques',16) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.categories (id,section_id,name,slug,sort_order) values ('0b128fb9-7a48-5d4c-9e6c-89ae6f744210','3d1e6e7b-9bb5-5177-ad0a-d2657c8b1977','Roc - Medusa', 'roc-medusa',17) on conflict (section_id,slug) do update set name=excluded.name,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c13334b7-87e4-516b-8a3e-5fe17b480077','4e393434-1103-53d7-a55b-c9f7b6e08a29','!nitro','!nitro','بيبعت ريوارد 1 Nitro Boost - Title Only.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('f860c9c9-591b-57be-ba0b-e24842d12a78','4e393434-1103-53d7-a55b-c9f7b6e08a29','!nitro2','!nitro2','بيبعت ريوارد 1 Nitro Boost يشمل Avatar و Pet و Title.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('574da470-d889-5b0d-ac63-b1d2799b6e2d','4e393434-1103-53d7-a55b-c9f7b6e08a29','!removenitro CharName','!removenitro CharName','بيعمل Remove للـ Nitro Title من الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d45c5e6a-843f-512e-8e29-8fd44f9aaa13','4e393434-1103-53d7-a55b-c9f7b6e08a29','!supporter CharName','!supporter CharName','بيضيف Supporter Title للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('64f50651-25de-580b-83bc-be789c0c6026','4e393434-1103-53d7-a55b-c9f7b6e08a29','!removesupporter CharName','!removesupporter CharName','بيشيل Supporter Title من الكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('8e54a046-c30e-5670-b248-2278c60b3b0c','4e393434-1103-53d7-a55b-c9f7b6e08a29','!streamer','!streamer','بيضيف Streamer Title / Role للكراكتر المحدد حسب إعدادات النظام.',false,'{}'::jsonb,'[]'::jsonb,5) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('360d9818-d9dc-5fe8-ae38-d536a92924e2','4e393434-1103-53d7-a55b-c9f7b6e08a29','!removestreamer','!removestreamer','بيشيل Streamer Title / Role من الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,6) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('0bb5d81d-27f9-599f-94ea-25f98e384751','4e393434-1103-53d7-a55b-c9f7b6e08a29','!tiktok %','!tiktok %','بيضيف TikTok Title أو Tag للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,7) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c7a29d36-4ce9-5727-b22f-db3322342c9f','4e393434-1103-53d7-a55b-c9f7b6e08a29','!removetiktok %','!removetiktok %','بيشيل TikTok Title أو Tag من الكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,8) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('576d5f89-be08-5682-8104-3d5382b1d651','4e393434-1103-53d7-a55b-c9f7b6e08a29','!kick %','!kick %','بيضيف Kick Title أو Tag للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,9) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c55eb893-13e2-54d2-9747-b4165fed7d19','4e393434-1103-53d7-a55b-c9f7b6e08a29','!removekick %','!removekick %','بيشيل Kick Title أو Tag من الكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,10) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('e927315d-0c50-573b-97b3-be8ed57fccc6','4e393434-1103-53d7-a55b-c9f7b6e08a29','!youtuber CharName','!youtuber CharName','بيضيف YouTuber Title أو Tag للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,11) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('95bb2b65-52de-5286-a249-49289e799d7a','4e393434-1103-53d7-a55b-c9f7b6e08a29','!removeyoutuber CharName','!removeyoutuber CharName','بيشيل YouTuber Title أو Tag من الكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,12) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('83372a3a-d777-5703-a23f-efb10a208780','4e393434-1103-53d7-a55b-c9f7b6e08a29','!twitch CharName','!twitch CharName','بيضيف Twitch Title أو Tag للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,13) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('2934720b-e69e-5237-9d56-90928f2fdb0b','4e393434-1103-53d7-a55b-c9f7b6e08a29','!removetwitch CharName','!removetwitch CharName','بيشيل Twitch Title أو Tag من الكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,14) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('aac6181e-ffa4-5d09-aae8-695274c5693d','4fce5718-428f-531d-be8f-8112d3d41311','!addsilkbyid','!addsilkbyid','بيبعت Silk بالـ ID. اكتب الكوماند ثم الـ ID ثم كمية الـ Silk.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('5802899c-3a3a-51dd-8c77-02343b46bffb','4fce5718-428f-531d-be8f-8112d3d41311','!addgiftbyid','!addgiftbyid','بيبعت Gift بالـ ID. اكتب الكوماند ثم الـ ID ثم كمية الـ Gift.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('8fd1430e-5fbb-57dc-ba58-b9485b2e5d45','4fce5718-428f-531d-be8f-8112d3d41311','!addsilkbyname','!addsilkbyname','بيبعت Silk باستخدام اسم الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('7531445e-45d1-5a3c-a94f-31c29b73964c','4fce5718-428f-531d-be8f-8112d3d41311','!addgiftbyname','!addgiftbyname','بيبعت Gift باستخدام اسم الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('af486b29-aac5-556a-ae80-1fab1029e39a','4fce5718-428f-531d-be8f-8112d3d41311','!pack CharName','!pack CharName','بيبعت Starter Package للكراكتر، ولازم يكون Online.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c2630f58-69f0-572a-8978-436b4565a9d6','4fce5718-428f-531d-be8f-8112d3d41311','!pack2 CharName','!pack2 CharName','بيبعت Starter Package للكراكتر سواء Online أو Offline.',false,'{}'::jsonb,'[]'::jsonb,5) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c0d7cd4e-3d9c-53db-b17f-82ef6a0eee20','4fce5718-428f-531d-be8f-8112d3d41311','!pack7','!pack7','بيبعت Package لمدة 7 أيام.',false,'{}'::jsonb,'[]'::jsonb,6) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d621634e-5cc0-5496-a46c-97014e4f81e2','4fce5718-428f-531d-be8f-8112d3d41311','!gold','!gold','بيبعت Gold للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,7) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('3629189c-7d80-5a24-ac5a-002b391bb455','9c9a9eba-09e3-5c63-9df2-2e4b773f6dfb','!pr %','!pr %','بيبعت الشار إلى Prison.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('582cc0e7-affd-5288-8e3a-f88ea3453755','9c9a9eba-09e3-5c63-9df2-2e4b773f6dfb','!unpr %','!unpr %','بيرجع الشار من Prison إلى Town.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('32a42a6d-b09e-5023-af6a-f9a047e41d7b','9c9a9eba-09e3-5c63-9df2-2e4b773f6dfb','!JobName %','!JobName %','بيجيب الـ Real Character Name من اسم الـ Job.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('7e505d81-5874-5232-9554-e6850e752748','9c9a9eba-09e3-5c63-9df2-2e4b773f6dfb','!resetpw %','!resetpw %','بيعمل Reset للـ Password الخاصة بالكراكتر.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('cbe0a3c6-9553-527a-b79e-273e45df83ba','9c9a9eba-09e3-5c63-9df2-2e4b773f6dfb','!addbp %','!addbp %','بيضيف Battle Pass Points للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('54cf166b-d894-5677-9820-16cc405f4659','a9b982f6-a70b-5465-93a7-08edae95bafd','!solodungeon %','!solodungeon %','بيخلص Quest الـ Solo Dungeon للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('5c66795a-2260-573c-99b7-3a9c427964d3','a9b982f6-a70b-5465-93a7-08edae95bafd','!garden %','!garden %','بيخلص Quest الـ Garden للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('9abab8e2-e32c-544c-8fa4-ee5ebb5734b3','a9b982f6-a70b-5465-93a7-08edae95bafd','!baghdad %','!baghdad %','بيخلص Quest بغداد للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('4fdf86c8-0beb-56ab-97d6-43b82d75532c','a9b982f6-a70b-5465-93a7-08edae95bafd','!DGQuest CharName','!DGQuest CharName','بيخلص Quest الـ Party Dungeon للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('9de9f7b8-eff4-53ac-9617-7ffd994a6e9c','a9b982f6-a70b-5465-93a7-08edae95bafd','!DGQuestReset CharName','!DGQuestReset CharName','بيعمل Reset للـ Limit الخاص بالـ Party Dungeon.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('345516ae-9904-5dfe-b2ae-a1e40a2e3d66','a9b982f6-a70b-5465-93a7-08edae95bafd','!HWTQuest CharName','!HWTQuest CharName','بيخلص Quest الـ HWT للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,5) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('76fc2dcf-a5e2-5a65-98f9-03ed3a311392','a9b982f6-a70b-5465-93a7-08edae95bafd','!HWTQuestReset CharName','!HWTQuestReset CharName','بيعمل Reset للـ Limit الخاص بالـ HWT.',false,'{}'::jsonb,'[]'::jsonb,6) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('9db5d0ba-924b-5f9c-989d-03744cf50dd7','a9b982f6-a70b-5465-93a7-08edae95bafd','!BAGQuest CharName','!BAGQuest CharName','بيخلص Quest بغداد Party للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,7) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('7b49812c-fb6d-578f-88c8-66dfa58ba02b','a9b982f6-a70b-5465-93a7-08edae95bafd','!BAGQuestReset CharName','!BAGQuestReset CharName','بيعمل Reset للـ Limit الخاص ببغداد Party.',false,'{}'::jsonb,'[]'::jsonb,8) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('e19f0cdd-0040-5a27-b497-535ddad3f019','47c36348-6a9c-5b8b-88e5-03d9991b08b4','!addjibril %','!addjibril %','بيضيف Card Jibril للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('7a4036a5-bc43-5531-87d7-063efaf94c33','47c36348-6a9c-5b8b-88e5-03d9991b08b4','!addice %','!addice %','بيضيف Ice Card للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('844aef70-2b1e-5e8f-9891-b0313b7b56d1','47c36348-6a9c-5b8b-88e5-03d9991b08b4','!addpoison %','!addpoison %','بيضيف Poison Card للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('b00ec03b-aea9-5e6c-920b-2fe9b9b0e37b','47c36348-6a9c-5b8b-88e5-03d9991b08b4','!addfire %','!addfire %','بيضيف Fire Card للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('a54f1651-b174-58a0-9a1f-f24425281e25','47c36348-6a9c-5b8b-88e5-03d9991b08b4','!addhuman %','!addhuman %','بيضيف Human Card للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('30dd8f45-f244-570f-a45f-9ce27d14cc0b','47c36348-6a9c-5b8b-88e5-03d9991b08b4','!addmichael %','!addmichael %','بيضيف Michael Card للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,5) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('cbc20991-a7f3-5145-877f-fc591d34124d','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!PCBanCharacter CharName','!PCBanCharacter CharName','بيعمل PC Ban للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d72f329e-95ad-5e98-bfca-92b40636b631','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!PCUnbanCharacter CharName','!PCUnbanCharacter CharName','بيشيل الـ PC Ban من الكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('05c64efc-da77-5c60-8938-9f79a2ab7a14','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!IPBanCharacter CharName','!IPBanCharacter CharName','بيعمل IP Ban للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('7a9e4c1d-0598-5a1d-aa01-e63f7cabc8ca','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!IPUnbanCharacter CharName','!IPUnbanCharacter CharName','بيشيل الـ IP Ban من الكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('ef9bc75e-0661-5ad5-9801-e1de8495f964','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!BanCharacter CharName','!BanCharacter CharName','بيعمل Ban للكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('935b56ff-393f-572a-8da7-48b6a442a553','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!UnbanCharacter CharName','!UnbanCharacter CharName','بيشيل الـ Ban من الكراكتر المحدد.',false,'{}'::jsonb,'[]'::jsonb,5) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('b51a4dee-bba6-5818-bdd3-902486313627','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!globalban CharName Days','!globalban CharName Days','بيعمل Global Ban للكراكتر لمدة عدد الأيام المحدد.',false,'{}'::jsonb,'[]'::jsonb,6) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('4da03f49-5a2e-57e6-880d-ab665e2747d9','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!unbanglobal CharName','!unbanglobal CharName','بيشيل الـ Global Ban من الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,7) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('8e6b3300-dbb0-5ed2-9c9a-2048614c52fd','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!chatban CharName Days','!chatban CharName Days','بيعمل Chat Ban للكراكتر لمدة عدد الأيام المحدد.',false,'{}'::jsonb,'[]'::jsonb,8) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('264414f0-d429-548a-a860-690056d0d3fe','fe32aad1-0c98-55dc-9da1-ae617a5458ba','!unbanchat CharName','!unbanchat CharName','بيشيل الـ Chat Ban من الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,9) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d747ea9b-ce42-5028-9c5e-b7caefb25a56','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!nitro','!nitro','بيدي للكراكتر Nitro Icon + Title، حسب اختيار In-game أو Bot.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('6ea73ed1-c70a-500b-a176-362d6c2debd0','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!nitro2','!nitro2','بيدي للكراكتر Nitro Icon + Title + Avatar + Pet، حسب اختيار In-game أو Bot.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d0d11b73-88d0-50ce-b825-090d8841a86d','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!tiktok %','!tiktok %','بيضيف TikTok Title أو Tag للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('4b539e34-06d8-52d1-a1b1-20858f175424','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!youtuber %','!youtuber %','بيضيف YouTuber Title أو Tag للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('2c50a99d-3909-5c5e-8230-829d3f56a8e2','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!twitch %','!twitch %','بيضيف Twitch Title أو Tag للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('df242066-20d1-5d35-a793-5ea1d5ad206e','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!supporter %','!supporter %','بيضيف Supporter Title أو Tag للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,5) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('47c8296f-8ae9-5426-8bc0-53a028cb56c8','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!removeyoutuber CharName','!removeyoutuber CharName','بيشيل YouTuber Title أو Tag من الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,6) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('0a64ec72-5e6f-5068-8196-8b98126cfc12','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!removenitro CharName','!removenitro CharName','بيشيل Nitro Title / Icon من الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,7) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('3236d6d3-2871-5671-a063-5d7f97d1ad64','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!removetwitch CharName','!removetwitch CharName','بيشيل Twitch Title أو Tag من الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,8) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d539c821-84a7-539c-b770-f7933830ae0f','17b60f5a-6a52-5fd9-ba80-24ff312e3ac3','!addtitle CharName %','!addtitle CharName %','بيضيف Title مخصص للكراكتر باستخدام القيمة المحددة.',false,'{}'::jsonb,'[]'::jsonb,9) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('328ffa57-358f-579f-8068-b2ddd209406f','97c4693d-56e8-5d8b-b0d3-0f2fed59201d','!addsilk2 UserName Amount','!addsilk2 UserName Amount','بيضيف Silk للمستخدم باستخدام الـ ID والكمية المحددة.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d5dd3aa7-8dc5-5692-9d27-957beea92f3e','97c4693d-56e8-5d8b-b0d3-0f2fed59201d','!addgift2 UserName Amount','!addgift2 UserName Amount','بيضيف Gift للمستخدم باستخدام الـ ID والكمية المحددة.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c78a7a67-d4bd-5929-8040-01578f0e5269','97c4693d-56e8-5d8b-b0d3-0f2fed59201d','!silk CharName Amount','!silk CharName Amount','بيضيف Silk للكراكتر باستخدام اسم الكراكتر والكمية.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('aa36cdae-6f79-5fee-9586-6439865146b7','97c4693d-56e8-5d8b-b0d3-0f2fed59201d','!gift CharName Amount','!gift CharName Amount','بيبعت Gift للكراكتر باستخدام اسم الكراكتر والكمية.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('8dd3951f-9357-5274-b421-b8739c445d98','79c61f24-501f-58fa-bfa8-45b05d94be29','!unstuck %','!unstuck %','بيفك الكراكتر لو عالق أو غير قادر على الحركة بشكل طبيعي.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('f0aa2124-57d3-513c-8b02-269109690518','79c61f24-501f-58fa-bfa8-45b05d94be29','!plvl CharName Level','!plvl CharName Level','بيحدد Level للكراكتر مباشرة بالمستوى المطلوب.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('cb31166b-30ae-5908-bc89-6c7c3179e417','79c61f24-501f-58fa-bfa8-45b05d94be29','!dc CharName','!dc CharName','بيعمل Disconnect للكراكتر المحدد من السيرفر.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('bb183851-525d-5f8e-8442-4728958e8da2','79c61f24-501f-58fa-bfa8-45b05d94be29','!addrankpoint CharName Amount','!addrankpoint CharName Amount','بيضيف Rank Points للكراكتر بالكمية المحددة.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('0a3cf5d4-1cd8-5dce-a2b4-7429d2800754','e606ab8f-bee5-58c9-ad0e-14983be1a926','!RandStats','!RandStats','بيعمل Random Stats للـ Item الموجود في الـ Inventory.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('5ab1bdff-f0ce-551b-a388-aea6402cbb41','e606ab8f-bee5-58c9-ad0e-14983be1a926','!clean','!clean','بيمسح كل الـ Items من الـ Inventory والـ Storage للكراكتر.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('f01debd0-2dfe-5344-8eed-b5841dec807c','e606ab8f-bee5-58c9-ad0e-14983be1a926','!removechestlog','!removechestlog','بيمسح الـ Chest Log الخاص بالكراكتر.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d8e4e961-7c51-5013-91ca-b63c79bc6f12','e606ab8f-bee5-58c9-ad0e-14983be1a926','!randelixir','!randelixir','بيملى الـ Inventory بـ Random Elixirs.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('e2ac6840-ac21-59f1-b87b-7c97c43fe0c5','e606ab8f-bee5-58c9-ad0e-14983be1a926','!copyitem','!copyitem','بيعمل Copy للـ Item، ولازم الـ Item يكون موجود في Slot 1 من الـ Inventory.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('47d48d20-1347-5340-a0d6-700abbafd401','32971820-af97-5614-830c-435b896bb1bb','!plusall 5','!plusall 5','بيطبق قيمة الـ Plus المحددة على الـ Items حسب إعداد الأمر.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('af301bff-6130-5d8c-b18f-265d67624819','32971820-af97-5614-830c-435b896bb1bb','!fball 0','!fball 0','FB Full.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('51d10109-0374-5011-87b1-c527ae982e1f','32971820-af97-5614-830c-435b896bb1bb','!fball 0 3','!fball 0 3','بيضيف Max Dur + 1 Immortal + 1 Astral.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('f372488f-a992-51e3-9844-a87ab0ee84f7','32971820-af97-5614-830c-435b896bb1bb','!fball 0 1','!fball 0 1','بيضيف Adv + Max Dur + 1 Immortal + 1 Astral.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('a7c5630f-1a6c-5404-b30e-54b0497d435d','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/invisible','/invisible','بيظهر أو يخفي الكراكتر.',false,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('8a1decf3-bfdb-50df-bd39-f372d797fdb8','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/invincible','/invincible','بيخلي الكراكتر غير قابل للضرب من الموبس أو اللاعبين.',false,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c5a71025-e178-56e9-99aa-0202ce12c900','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/camera','/camera','GM Camera.',false,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('88b71143-2797-54ce-96ec-763e90f00ad8','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/ban CharacterName','/ban CharacterName','بيعمل Disconnect للاعب.',false,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('0f4bb9d1-7346-5ac1-b569-bf7d11639672','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/recalluser CharacterName','/recalluser CharacterName','بيسحب اللاعب جنبك.',false,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('40ac832d-fa25-551f-9d4f-643a10b2351a','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/movetouser CharacterName','/movetouser CharacterName','بينقلك جنب اللاعب.',false,'{}'::jsonb,'[]'::jsonb,5) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d643acea-ad5b-5aeb-81ba-825bff2c5e03','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/recallguild GuildName','/recallguild GuildName','بيسحب الجيلد بالكامل جنبك.',false,'{}'::jsonb,'[]'::jsonb,6) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('e2f5adee-5eda-59eb-88a5-b13f17f89149','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/gotown','/gotown','بينقلك للـ Town.',false,'{}'::jsonb,'[]'::jsonb,7) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('8117dd64-862a-5e23-830f-c1dfb95a957f','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/totown CharacterName','/totown CharacterName','بيودي اللاعب للـ Town.',false,'{}'::jsonb,'[]'::jsonb,8) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('7a0654b4-6bf6-5d41-b327-7494853d08ab','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/mobkill0','/mobkill0','بيقتل Mob أو Unique.',false,'{}'::jsonb,'[]'::jsonb,9) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('b7938432-27f9-5295-b142-68ca06e0b622','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/mobkill1','/mobkill1','بيخفي Mob أو Unique.',false,'{}'::jsonb,'[]'::jsonb,10) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('2e979730-9ece-5853-a8bc-89231ce64c2c','df70df0f-ac66-5886-bfd2-8571dd41cb2c','/gmskill0','/gmskill0','Skill الدايرة الخاصة بالـ GM.',false,'{}'::jsonb,'[]'::jsonb,11) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('82c260ae-bfda-5470-8f9c-b02b6db7673a','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Tigerwoman - EU - INT','/loadmonster MOB_EU_TIGERWOMAN_EU_INT','EU / INT',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('16926183-e6b5-5ff1-bebd-083f954532ec','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Tigerwoman - EU - STR','/loadmonster MOB_EU_TIGERWOMAN_EU_STR','EU / STR',true,'{}'::jsonb,'[]'::jsonb,1) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('3af9b895-911e-5cf4-bdc2-19c33ee983c5','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Kerberos - EU - INT','/loadmonster MOB_EU_KERBEROS_EU_INT','EU / INT',true,'{}'::jsonb,'[]'::jsonb,2) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('fe00c4ed-d6f3-5e98-bb81-f29ab1a48351','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Kerberos - EU - STR','/loadmonster MOB_EU_KERBEROS_EU_STR','EU / STR',true,'{}'::jsonb,'[]'::jsonb,3) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('16e55262-c12c-5aac-b67c-313c241ed0a9','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Ivy - EU - INT','/loadmonster MOB_AM_IVY_EU_INT','EU / INT',true,'{}'::jsonb,'[]'::jsonb,4) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('b7ac41de-1992-5e8e-9b62-9b125c5fb587','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Ivy - EU - STR','/loadmonster MOB_AM_IVY_EU_STR','EU / STR',true,'{}'::jsonb,'[]'::jsonb,5) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('53913a36-cc80-5f9c-b29c-487733187199','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Urueui - EU - INT','/loadmonster MOB_OA_URUEUI_EU_INT','EU / INT',true,'{}'::jsonb,'[]'::jsonb,6) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('2f98212b-1156-5172-b4eb-9db5bb1eb7b9','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Urueui - EU - STR','/loadmonster MOB_OA_URUEUI_EU_STR','EU / STR',true,'{}'::jsonb,'[]'::jsonb,7) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('5af756f4-7b29-5b6f-ade6-7b672f15bb1c','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Isyutaru - EU - INT','/loadmonster MOB_KK_ISYUTARU_EU_INT','EU / INT',true,'{}'::jsonb,'[]'::jsonb,8) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('346c0f48-14eb-5a2d-afb6-c0b3a23b3d2d','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Isyutaru - EU - STR','/loadmonster MOB_KK_ISYUTARU_EU_STR','EU / STR',true,'{}'::jsonb,'[]'::jsonb,9) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('0570b327-1831-570e-9e51-56fba87213f7','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Bonelord - EU - INT','/loadmonster MOB_TK_BONELORD_EU_INT','EU / INT',true,'{}'::jsonb,'[]'::jsonb,10) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('34e6bc3d-4ee9-5350-ac39-cf7921f939a3','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Bonelord - EU - STR','/loadmonster MOB_TK_BONELORD_EU_STR','EU / STR',true,'{}'::jsonb,'[]'::jsonb,11) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('33084272-36e2-59f8-8f38-9b194b6e7c42','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Tahomet - EU - INT','/loadmonster MOB_RM_TAHOMET_EU_INT','EU / INT',true,'{}'::jsonb,'[]'::jsonb,12) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('dfa580e3-b61a-5e77-a50c-e890cc2577ef','7c9a958e-f7b6-5c39-9fe2-02219c52dff7','Tahomet - EU - STR','/loadmonster MOB_RM_TAHOMET_EU_STR','EU / STR',true,'{}'::jsonb,'[]'::jsonb,13) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('ab16717d-a94e-5f0f-88df-b8ff690a2d75','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Tigerwoman - CH - INT','/loadmonster MOB_CH_TIGERWOMAN_CH_INT','CH / INT',true,'{}'::jsonb,'[]'::jsonb,14) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('b18b7327-b91c-505d-95b2-18190d4cfd0f','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Tigerwoman - CH - STR','/loadmonster MOB_CH_TIGERWOMAN_CH_STR','CH / STR',true,'{}'::jsonb,'[]'::jsonb,15) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('e4843b88-9219-5098-b95e-67d9bc805c90','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Kerberos - CH - INT','/loadmonster MOB_EU_KERBEROS_CH_INT','CH / INT',true,'{}'::jsonb,'[]'::jsonb,16) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('4a143309-a7d9-59a4-add7-13dd70ba84b6','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Kerberos - CH - STR','/loadmonster MOB_EU_KERBEROS_CH_STR','CH / STR',true,'{}'::jsonb,'[]'::jsonb,17) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('e32a6d0a-2d9a-57d8-a4a1-02f696ac428b','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Ivy - CH - INT','/loadmonster MOB_AM_IVY_CH_INT','CH / INT',true,'{}'::jsonb,'[]'::jsonb,18) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('013a1d1a-fc44-506c-ace3-baaf8f93b66d','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Ivy - CH - STR','/loadmonster MOB_AM_IVY_CH_STR','CH / STR',true,'{}'::jsonb,'[]'::jsonb,19) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('2b81cc78-384a-5b7f-9007-9b4003f6f97f','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Uruchi - CH - INT','/loadmonster MOB_OA_URUCHI_CH_INT','CH / INT',true,'{}'::jsonb,'[]'::jsonb,20) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('143ec8a2-3c38-5c16-97d7-494597bbb603','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Uruchi - CH - STR','/loadmonster MOB_OA_URUCHI_CH_STR','CH / STR',true,'{}'::jsonb,'[]'::jsonb,21) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('7968048d-afa9-5c26-ad05-905b910aacd1','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Isyutaru - CH - INT','/loadmonster MOB_KK_ISYUTARU_CH_INT','CH / INT',true,'{}'::jsonb,'[]'::jsonb,22) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('e16d40bf-614f-5e16-bda3-55be9a74c046','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Isyutaru - CH - STR','/loadmonster MOB_KK_ISYUTARU_CH_STR','CH / STR',true,'{}'::jsonb,'[]'::jsonb,23) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('f5eade84-dcc0-509d-bbf7-fe98e2742ba1','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Bonelord - CH - INT','/loadmonster MOB_TK_BONELORD_CH_INT','CH / INT',true,'{}'::jsonb,'[]'::jsonb,24) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('9a28fa26-f392-5108-ada0-031f0f2ff52c','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Bonelord - CH - STR','/loadmonster MOB_TK_BONELORD_CH_STR','CH / STR',true,'{}'::jsonb,'[]'::jsonb,25) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('b8eb6e92-a31c-5e41-93bc-d1a7a2645b8e','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Tahomet - CH - INT','/loadmonster MOB_RM_TAHOMET_CH_INT','CH / INT',true,'{}'::jsonb,'[]'::jsonb,26) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('344151ee-dd2a-5e3b-9cbf-49b55ef36890','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Tahomet - CH - STR','/loadmonster MOB_RM_TAHOMET_CH_STR','CH / STR',true,'{}'::jsonb,'[]'::jsonb,27) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c0d445c3-a85f-526a-a52f-c6b75f775f7b','a4eda4e6-ee67-53c3-a860-8b1ff9e1aeee','Zerk','/loadmonster MOB_FW_TAESE_001','Zerk Unique.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('b88cf75f-d0ef-56ed-895e-18e10aebd721','85314461-a38c-592f-84c5-9ea7f23e4c18','Babilion','/loadmonster MOB_JUPITER_BABILION','Zealot Unique.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('ea893bb7-231a-5044-8b8a-408796420bf5','85314461-a38c-592f-84c5-9ea7f23e4c18','Jupiter','/loadmonster MOB_JUPITER_JUPITER','Zealot Unique.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('7c161269-c5dc-5c49-8028-5eb3e2f4096f','85314461-a38c-592f-84c5-9ea7f23e4c18','Yuno - STR','/loadmonster MOB_JUPITER_YUNO','STR.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('4a599d60-2f5f-53bf-9168-ed7cc387a748','85314461-a38c-592f-84c5-9ea7f23e4c18','Dark Dog - STR','/loadmonster MOB_JUPITER_DARK_DOG','STR.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('71eb47e5-a92e-5089-8081-6684cb5499b3','85314461-a38c-592f-84c5-9ea7f23e4c18','Zerk','/loadmonster MOB_FW_TAESE_001','Zerk Unique.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('548594c6-0b90-5639-bc9e-a1b85fa218b4','5b2bef5d-9145-5b55-8a78-16acea9d24b8','Anubis','/loadmonster MOB_SD_ANUBIS','Temple Unique.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('fa01af61-9d09-50f3-939a-397e6390854c','5b2bef5d-9145-5b55-8a78-16acea9d24b8','Neith','/loadmonster MOB_SD_NEITH','Temple Unique.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('d482a135-0293-55e9-8e46-f60527531c13','5b2bef5d-9145-5b55-8a78-16acea9d24b8','Isis - STR','/loadmonster MOB_SD_ISIS','STR.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('53fc9c45-edfd-5f12-b65f-25fb5e0f7efb','5b2bef5d-9145-5b55-8a78-16acea9d24b8','Selkis','/loadmonster MOB_SD_SELKIS','Temple Unique.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('56e3038e-f5f5-5bc4-a4d7-9820fa0e5b0a','5b2bef5d-9145-5b55-8a78-16acea9d24b8','Zerk','/loadmonster MOB_FW_TAESE_001','Zerk Unique.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('074eaadb-d0dd-5952-804f-4ac42d9f65f0','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Whitesnake - CH - STR','/loadmonster MOB_TQ_WHITESNAKE_CH_STR','Medusa Party / CH / STR.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c7672dc2-af15-5df8-9218-5271c62de2c5','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Whitesnake - CH - INT','/loadmonster MOB_TQ_WHITESNAKE_CH_INT','Medusa Party / CH / INT.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c24132af-6047-5b81-a7d3-3c93afe78092','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Whitesnake - EU - STR','/loadmonster MOB_TQ_WHITESNAKE_EU_STR','Medusa Party / EU / STR.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('8eb70cef-c229-5a11-bddf-e03bab0ba45e','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Whitesnake - EU - INT','/loadmonster MOB_TQ_WHITESNAKE_EU_INT','Medusa Party / EU / INT.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('514d0d02-c305-5c57-8d38-b109c0828e23','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Roc - CH - STR','/loadmonster MOB_RM_ROC_CH_STR','Roc / CH / STR.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('96e47e2b-920d-534a-b012-67b99713a2a0','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Roc - CH - INT','/loadmonster MOB_RM_ROC_CH_INT','Roc / CH / INT.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('c409d7e6-8483-5a11-a4cd-691ed2f30ad3','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Roc - EU - STR','/loadmonster MOB_RM_ROC_EU_STR','Roc / EU / STR.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('59e6ac93-83ac-572c-9ead-c6de8e151cb4','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Roc - EU - INT','/loadmonster MOB_RM_ROC_EU_INT','Roc / EU / INT.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('09ba723e-fcc8-50dc-b2e2-64d48b73b971','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Roc - HP','/loadmonster MOB_RM_ROC','HP كتير جدًا.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
insert into public.entries (id,category_id,name,code,description,uses_amount,variants,levels,sort_order) values ('3babd90b-9e96-5ae1-9fbf-b4b74876a8e4','0b128fb9-7a48-5d4c-9e6c-89ae6f744210','Bone Roc','/loadmonster MOB_RM_BONEROC','Death Bone Roc.',true,'{}'::jsonb,'[]'::jsonb,0) on conflict (id) do update set name=excluded.name,code=excluded.code,description=excluded.description,uses_amount=excluded.uses_amount,variants=excluded.variants,levels=excluded.levels,sort_order=excluded.sort_order;
commit;
