'use client'

import { useEffect, useMemo, useState } from 'react'
import { Plus, Save, Trash2, RefreshCw } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { Category, Entry, Section } from '@/lib/types'
import { slugify } from '@/lib/slug'

export default function AdminCommandEditor({sections,initialSection,initialCategory}:{sections:Section[];initialSection?:string;initialCategory?:string}){
 const supabase=createClient(); const [local,setLocal]=useState(sections); const [sectionSlug,setSectionSlug]=useState(initialSection||sections[0]?.slug||'discord'); const [categoryId,setCategoryId]=useState(initialCategory||''); const current=local.find(s=>s.slug===sectionSlug)??local[0]; const categories=current?.categories??[]; const category=categories.find(c=>c.id===categoryId)||categories[0]; const [entryId,setEntryId]=useState(category?.entries[0]?.id||''); const entry=category?.entries.find(e=>e.id===entryId)||category?.entries[0];
 const [draft,setDraft]=useState({name:'',code:'',description:'',uses_amount:false,variants:'{}',levels:'[]'}); const [status,setStatus]=useState(''); const [saving,setSaving]=useState(false)
 useEffect(()=>{if(category){setCategoryId(category.id);setEntryId(category.entries[0]?.id||'')}},[sectionSlug])
 useEffect(()=>{if(entry)setDraft({name:entry.name,code:entry.code,description:entry.description,uses_amount:entry.uses_amount,variants:JSON.stringify(entry.variants||{},null,2),levels:JSON.stringify(entry.levels||[],null,2)})},[entryId,categoryId,local])
 const isAdd = entryId==='__new__'
 async function refresh(){ const {data}=await supabase.from('sections').select('id,name,slug,description,kind,sort_order,categories(id,name,slug,sort_order,entries(id,name,code,description,uses_amount,variants,levels,sort_order))').order('sort_order'); if(data)setLocal(data as unknown as Section[]) }
 function startAdd(){setEntryId('__new__');setDraft({name:'',code:'',description:'',uses_amount:false,variants:'{}',levels:'[]'});setStatus('')}
 async function save(){if(!category)return;setSaving(true);setStatus('');try{let variants={};let levels:string[]=[];try{variants=JSON.parse(draft.variants||'{}')}catch{throw new Error('Variants must be valid JSON')}try{levels=JSON.parse(draft.levels||'[]')}catch{throw new Error('Levels must be valid JSON')}
  if(isAdd){const max=Math.max(-1,...category.entries.map(e=>e.sort_order));const {data,error}=await supabase.from('entries').insert({category_id:category.id,name:draft.name,code:draft.code,description:draft.description,uses_amount:draft.uses_amount,variants,levels,sort_order:max+1}).select().single();if(error)throw error;setEntryId(data.id);}
  else {const {error}=await supabase.from('entries').update({name:draft.name,code:draft.code,description:draft.description,uses_amount:draft.uses_amount,variants,levels}).eq('id',entryId);if(error)throw error}
  setStatus('Saved.');await refresh()
 }catch(e){setStatus(e instanceof Error?e.message:'Could not save.')}finally{setSaving(false)}}
 async function remove(){if(isAdd||!entry)return;if(!confirm(`Delete ${entry.name}?`))return;const {error}=await supabase.from('entries').delete().eq('id',entry.id);setStatus(error?error.message:'Deleted.');if(!error){await refresh();setEntryId('')}}
 return <div className="admin-grid"><aside className="admin-nav"><div className="muted" style={{padding:'10px 12px',fontSize:11,fontWeight:800}}>SECTIONS</div>{local.map(s=><button key={s.id} className={`choice ${current?.slug===s.slug?'active':''}`} onClick={()=>setSectionSlug(s.slug)}>{s.name}</button>)}</aside><main className="admin-card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'}}><div><div className="eyebrow">COMMAND MANAGER</div><h1>{current?.name}</h1><p className="muted">Manage categories and entries live.</p></div><button className="ghost-btn" onClick={refresh}><RefreshCw size={16}/> Refresh</button></div><div className="form-grid" style={{marginTop:20}}><div className="field"><label>CATEGORY</label><select value={category?.id||''} onChange={e=>{setCategoryId(e.target.value);const c=categories.find(x=>x.id===e.target.value);setEntryId(c?.entries[0]?.id||'')}}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>ENTRY</label><select value={isAdd?'__new__':entry?.id||''} onChange={e=>setEntryId(e.target.value)}><option value="__new__">+ Add new entry</option>{category?.entries.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div></div><div className="form-grid" style={{marginTop:20}}><div className="field"><label>NAME</label><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></div><div className="field"><label>COMMAND / CODE</label><input value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></div><div className="field" style={{gridColumn:'1 / -1'}}><label>DESCRIPTION</label><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></div><div className="field"><label>VARIANTS JSON</label><textarea value={draft.variants} onChange={e=>setDraft({...draft,variants:e.target.value})}/></div><div className="field"><label>LEVELS JSON</label><textarea value={draft.levels} onChange={e=>setDraft({...draft,levels:e.target.value})}/></div></div><label style={{display:'flex',gap:8,alignItems:'center',marginTop:12,fontSize:12,color:'#b8c1ca'}}><input type="checkbox" checked={draft.uses_amount} onChange={e=>setDraft({...draft,uses_amount:e.target.checked})}/> Uses amount</label><div style={{display:'flex',gap:10,marginTop:18}}><button className="primary-btn" onClick={save} disabled={saving}><Save size={16}/>{saving?'Saving…':'Save entry'}</button>{!isAdd&&<button className="danger-btn" onClick={remove}><Trash2 size={16}/>Delete</button>}<button className="ghost-btn" onClick={startAdd}><Plus size={16}/>New</button></div>{status&&<div style={{marginTop:14,color:status==='Saved.'||status==='Deleted.'?'#32c67a':'#ff8a8a',fontSize:12}}>{status}</div>}</main></div>
}
